Try to fix tilt...
you get:
```
Error: Error watching events. Are you connected to kubernetes?
Try running `kubectl get events -n "default"`: WatchEvents: makeInformer: the server rejected our request due to an error in our request, Reason: Invalid, Code: 422
```

against a new cluster now... maybe new events api it is failing on?

Signed-off-by: clux <sszynrae@gmail.com>